from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'starttb30{CMD_INDEX}'
        self.MirrorCommand = f'mirrortb30{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirrortb30{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirrortb30{CMD_INDEX}'
        self.CancelMirror = f'canceltb30{CMD_INDEX}'
        self.CancelAllCommand = f'cancelalltb30{CMD_INDEX}'
        self.ListCommand = f'listtb30{CMD_INDEX}'
        self.SearchCommand = f'searchtb30{CMD_INDEX}'
        self.StatusCommand = f'statustb30{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'userstb30{CMD_INDEX}'
        self.AuthorizeCommand = f'authorizetb30{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorizetb30{CMD_INDEX}'
        self.AddSudoCommand = f'addsudotb30{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudotb30{CMD_INDEX}'
        self.PingCommand = f'pingtb30{CMD_INDEX}'
        self.RestartCommand = f'restarttb30{CMD_INDEX}'
        self.StatsCommand = f'statstb30{CMD_INDEX}'
        self.HelpCommand = f'helptb30{CMD_INDEX}'
        self.LogCommand = f'logtb30{CMD_INDEX}'
        self.SpeedCommand = f'speedtesttb30{CMD_INDEX}'
        self.CloneCommand = f'clonetb30{CMD_INDEX}'
        self.CountCommand = f'counttb30{CMD_INDEX}'
        self.WatchCommand = f'watchtb30{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatchtb30{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmirrortb30{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirrortb30{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirrortb30{CMD_INDEX}'
        self.DeleteCommand = f'deltb30{CMD_INDEX}'
        self.ShellCommand = f'shelltb30{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelptb30{CMD_INDEX}'
        self.LeechSetCommand = f'leechsettb30{CMD_INDEX}'
        self.SetThumbCommand = f'setthumbtb30{CMD_INDEX}'
        self.LeechCommand = f'leechtb30{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleechtb30{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleechtb30{CMD_INDEX}'
        self.QbLeechCommand = f'qbleechtb30{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleechtb30{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleechtb30{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatchtb30{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatchtb30{CMD_INDEX}'
        self.RssListCommand = f'rsslisttb30{CMD_INDEX}'
        self.RssGetCommand = f'rssgettb30{CMD_INDEX}'
        self.RssSubCommand = f'rsssubtb30{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsubtb30{CMD_INDEX}'
        self.RssUnSubAllCommand = f'rssunsuballtb30{CMD_INDEX}'
        self.RssSettingsCommand = f'rsssettb30{CMD_INDEX}'
        self.WayBackCommand = f'waybacktb30{CMD_INDEX}'
        self.VirusTotalCommand = f'virustotaltb30{CMD_INDEX}'
        self.HashCommand = f'hashtb30{CMD_INDEX}'
        self.ShortenerCommand = f'shorttb30{CMD_INDEX}'
        self.MediaInfoCommand = f'mediainfotb30{CMD_INDEX}'

BotCommands = _BotCommands()
